weni-ai/insights-webapp

- src/router/index.js
- src/views/dashboards/Home/index.vue
- src/views/insights/Home/index.vue
Adding the base of the Dashboards page.
> Adding the Dashboards page

- src/components/DashboardsCard.vue
Creating the new card component for the main page Dashboards.
> Adding component dashboards card

- src/components/AgentChats.vue
> Feat: Adding agent chats component

- src/router/index.js
- src/views/dashboards/Dashboard/index.vue
> Feat: Adding the page for each single dashboard

- src/components/TableChats.vue
- src/components/TablePagination.vue
- src/mocks/chats.json
- src/views/dashboards/Home/index.vue
Add base template for table chats, with two components: table and pagination.
> Feat: Add table chats 

- .dockerignore
- .github/workflows/build-insights-webapp-push-tag-shared.yaml
- docker-entrypoint.sh
- docker/Dockerfile
- docker/nginx/nginx.conf
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Some files are necessary for the project image to be created and uploaded to an environment.
Docker files were added that contain the configuration and step-by-step image installation and also a workflow file for github to recognize and build.
> feat: Add config dockerfiles and workflow file

- src/components/DashboardsCard.vue
- src/mocks/dashboards.json
- src/views/dashboards/Home/index.vue
- src/views/insights/Home/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
It was necessary to add the cards to the Dashboards page.
The card component was added to the Dashboards page and the component has a redirection to another page. Some styles have also been adjusted.
- [Design File 1](https://www.figma.com/file/P9yyN4D0wGMlzYMjOtHvv3/Insights?type=design&node-id=1658-4287&mode=design&t=fsGsRmoAvaB1CMSs-0)
> feat: Add the cards on the dashboards page and adjust some styles

- src/layouts/InsightsLayout/index.vue
- src/views/insights/Home/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The spacing in the header was not following the prototype model.
- Adjusted the size of the spacing between items
- [Design File 1](https://www.figma.com/file/P9yyN4D0wGMlzYMjOtHvv3/Insights?type=design&node-id=2618-5262&mode=design&t=EPS4F4vw2GAKEB9C-0)
> fix: Adjusting the spacing according to the prototype

- src/components/AgentChats.vue
- src/components/ResizableBar.vue
- src/layouts/InsightsLayout/index.vue
- src/views/dashboards/Dashboard/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
The page grid of each dashboard needed to be consistent with the prototype.
The arrangement of items on the grid was separated so that it is 9x9.
- [Design File 1](https://www.figma.com/file/P9yyN4D0wGMlzYMjOtHvv3/Insights?type=design&node-id=2601-2&mode=design&t=3eMSlNUDPRWZ3i8E-0)
> fix: Improve the grid layout on a dashboard page

- src/App.vue
- src/components/DashboardsCard.vue
- src/components/InsightsMainCard.vue
- src/components/ResizableBar.vue
- src/components/connect/ConnectSidebar.vue
- src/components/connect/ConnectTopbar.vue
- src/views/dashboards/Dashboard/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Since we implemented eslint some code can be improved
- An improvement in the code was attributed using eslint rules
- The use of pascal case in component names
- Added the name of some components that were missing
> [ENGAGE-584] - Fixing the code using eslint

- src/components/InsightsCard.vue
- src/components/InsightsInput.vue
- src/components/ResizableBar.vue
- src/components/SugestionCard.vue
- src/layouts/InsightsLayout/index.vue
- src/main.js
- src/router/index.js
- src/store/index.js
- src/store/modules/sidebar.js
- src/views/insights/Home/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Adjust the drag function of the dragbar and the home page grid.
- Adding chart visibility on the main page in relation to the dragbar position using state
- Improve the style of some components using unnnic tokens
- Created a new card component for the dragbar
- Improving the position of the dragbar for each situation
- [Design File 1](https://www.figma.com/file/P9yyN4D0wGMlzYMjOtHvv3/Insights?type=design&node-id=1658-4144&mode=design&t=RUD8c2lYpNsmEzqR-0)
> [ENGAGE-594] - Adjust dragbar functionality and the home page grid

- src/components/BarChart.vue
- src/mocks/barChartData.json
- src/mocks/dashboards.json
- src/router/index.js
- src/views/dashboards/Dashboard/FlowTrigger.vue
- src/views/dashboards/Home/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
New dash page needs to be added.
- Added a new chart component
- Added a data mock to the chart
- Added a new route to the new page
- [Design File 1](https://www.figma.com/file/P9yyN4D0wGMlzYMjOtHvv3/Insights?type=design&node-id=2-3&mode=design&t=lbamPI6bJORzQSJk-0)
> [ENGAGE-644] -  Add new page flow trigger

- package.json
- src/App.vue
- src/components/insights/Layout/Header.vue
- src/components/insights/Layout/HeaderFilters/FiltersModalHumanService.vue
- src/components/insights/Layout/HeaderFilters/index.vue
- src/layouts/InsightsLayout.vue
- src/layouts/InsightsLayout/Header.vue
- src/layouts/InsightsLayout/HeaderFilters.vue
- src/router/index.js
- src/router/routes/dashboards.js
- src/router/routes/index.js
- yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Inicializado o componente InsightsLayoutHeader;
- Controle sobre a sobre a rota e suas queries a partir dos filtros do header;
- Filtros de atendimento humano.
- [Insights MVP](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?m=dev&node-id=3770%3A4803)
> [ENGAGE-810] - (Insights MVP) InsightsLayout header filters

- package.json
- src/components/insights/Layout/Header.vue
- src/components/insights/Layout/HeaderFilters/index.vue
- src/components/insights/Layout/HeaderSelectDashboard.vue
- src/components/insights/Layout/HeaderTagLive.vue
- src/router/routes/dashboards.js
- yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
(Insights MVP) The layout header needs design changes to better suit screens.
- Fixed sidebar icons updating unnnic version;
- Added breadcrumb at home;
- Created header select dashboard component;
- Added tag live to header if date filter is not-applied;
- Added export metrics button to header;
- Added clear filters button if has many filters.
- [Insights MVP](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?m=dev&node-id=3770%3A4803)
> [ENGAGE-893] - (Insights MVP) Layout header design fix

- src/components/Card.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
(Insights MVP) The card needs design changes to better suit screens.
- Adjusted Card styles.
- [Insights MVP](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?m=dev&node-id=3770%3A4803)
> [ENGAGE-853] - (Insights MVP) Fixed card styles

- src/components/ColumnCharts.vue
- src/layouts/InsightsLayout.vue
- src/utils/plugins/ApexCharts.js
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
(Insights MVP) The home design changes to better suit screens.
- Fixed InsightsLayout content padding;
- Adjusted column charts design.
>  [ENGAGE-853] - (Insights MVP) Fixed home design

- package.json
- src/components/insights/charts/BarChart.vue
- src/components/insights/charts/BaseChart.vue
- src/components/insights/charts/FunnelChart.vue
- src/utils/object.js
- yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Updated Unnnic to get ChartFunnel component;
- Removed vue-chartjs lib because funnel chart is not compatible with this;
- Adjusted ChartBase to use Chart.js native instead vue-chartjs;
- Created FunnelChart component.
- [Chart funnel component](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?node-id=3341-2670&t=qbAPadHThEmAVvDt-0)
> [ENGAGE-895] - (Insights MVP) Chart funnel

- src/components/insights/cards/CardBase.vue
- src/components/insights/cards/CardDashboard.vue
- src/components/insights/cards/CardFunnel.vue
- src/views/dashboards/HumanService.vue
- src/views/insights/Home/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Created CardBase component and based CardDashboard with it;
- Created CardFunnel component.
- [Card funnel](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?node-id=3341-2670&t=qbAPadHThEmAVvDt-0)
> [ENGAGE-895] - (Insights MVP) FunnelCard

- package.json
- src/App.vue
- src/components/insights/Layout/Header.vue
- src/components/insights/Layout/HeaderSelectDashboard.vue
- src/layouts/InsightsLayout.vue
- src/models/Dashboard.js
- src/models/index.js
- src/router/index.js
- src/services/api/customError.js
- src/services/api/http.js
- src/services/api/index.js
- src/services/api/resources/dashboards.js
- src/store/index.js
- src/store/modules/config.js
- src/store/modules/dashboards.js
- src/store/modules/gpt.js
- yarn.lock
* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Insights MVP
- Updated Axios version;
- Added anti-corruption layer to client;
- Created dashboard model;
- Fetch dashboards on App creation;
- Adjusted select dashboards to api data;
- Dashboard dynamic routes.
> [ENGAGE-935] - (Insights MVP) API mocks and models

- docker/Dockerfile
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
(Insights MVP) Due to the addition of the TypeScript package, a newer version of the node is now required to run the application.
- Changed the Dockerfile node version.
> [ENGAGE - 1000] - Fix of docker node version

- docker/nginx/nginx.conf
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Content-Security-Policy is the name of a HTTP response header that modern browsers use to enhance the security of the web document.
- Add include parameter to map csp headrs in nginx
> add mapping for csp on nginx

- src/App.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/models/Widget.ts
- src/models/types/WidgetTypes.ts
- src/router/index.js
- src/services/api/resources/dashboards.js
- src/views/insights/Dashboard.vue
- src/views/insights/Report.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Adjusted handler dashboard fetchs;
- Adjusted widgets loading status;
- First version of view report;
- Widgets redirect to report view.
> [ENGAGE-1017] - (Insights MVP) View report

- src/components/insights/Layout/HeaderSelectDashboard.vue
- src/services/api/resources/dashboards.js
- src/store/modules/dashboards.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Add favorite dashboard handling 
- [Design File 1](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?node-id=4637-3167&m=dev)
[Screencast from 2024-06-04 14-02-10.webm](https://github.com/weni-ai/insights-webapp/assets/25366317/6ee4ed0c-b5d2-49fe-bc83-4159e6d48612)
> [ENGAGE-1008] - Add favorite dashboard handling 

- src/layouts/InsightsLayout.vue
…content
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Insights MVP
- Removed connect remnants;
- Adjusted size of InsightsLayout content to occupy the entire height.
> [ENGAGE-1014] - (Insights MVP) Adjusted size of InsightsLayout

- src/components/insights/Layout/Header.vue
- src/router/index.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Removed useless routes;
- Breadcrumb routing and names
> [ENGAGE-1014] - (Insights MVP) Adjusted routing and names of breadcrumbs 

- src/components/insights/Layout/HeaderSelectDashboard.vue
- src/components/insights/Layout/HeaderTagLive.vue
- src/components/insights/cards/CardDashboard.vue
- src/components/insights/charts/BarChart.vue
- src/components/insights/charts/HorizontalBarChart.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/components/insights/widgets/TableDynamicByFilter.vue
- src/views/insights/Report.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Insights MVP
- Adjusted graph widgets and TableDynamicByFilter paddings and borders;
- Changed HeaderTagLive text from 'Ao Vivo' to 'Hoje';
- Adjusted CardDasboard gaps;
- Changed HeaderSelectDashbaord icon to arrow back when at report view
- [Design Review](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?m=dev&node-id=4250-5491)
> [ENGAGE-1014] - (Insights MVP) Design review

- src/components/insights/widgets/TableDynamicByFilter.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
Redirect item of table dynamic by filter if it has a link
> [ENGAGE-1007] - (Insights MVP) Redirect item of table dynamic by filter if it has a link

- src/components/insights/Layout/HeaderFilters/ModalFilters.vue
- src/components/insights/Layout/HeaderFilters/index.vue
- src/components/insights/widgets/TableGroup.vue
- src/store/modules/dashboards.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Created an action to reset the filters correctly;
- Fix keep old queries when changing tabs in TableGroup.
> [ENGAGE-1036] - (Insights MVP) Fix of clear route filters

- src/services/api/resources/dashboards.js
- src/services/api/resources/projects.js
- src/services/api/resources/widgets.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Pass project at query param in all dashboards endpoints;
- Added slash at the end of each endpoint.
> [ENGAGE-1038] - Fix all dashboard endpoints follow insights-engine pattern

- src/services/api/http.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
Intercept all requests to send auth tokens.
> [ENGAGE-1073] - (Insights MVP) Intercept all requests to send auth tokens

- src/components/insights/widgets/DynamicWidget.vue
- src/components/insights/widgets/TableGroup.vue
- src/services/api/resources/dashboards.js
- src/store/modules/config.js
- src/store/modules/reports.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
Added pagination of requests report data and applied it to TableGroup
> [ENGAGE-1073] - (Insights MVP) TableGroup pagination

- src/components/insights/widgets/DynamicWidget.vue
- src/components/insights/widgets/TableGroup.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- As the backend needed to be changed to return the TableGroup tab settings, this was changed on the frontend as well;
- Fixed TableGroup pagination requests
> [ENGAGE-1073] - (Insights MVP) Fix TableGroup requests

- package.json
- src/components/insights/Layout/HeaderFilters/index.vue
- src/router/index.js
- src/store/modules/dashboards.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
* Add date range filters default values
> [ENGAGE-1063] Add filter default values

- src/components/insights/widgets/DynamicWidget.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Transform data in a string before validate
> [ENGAGE-1073] - (Insights MVP) Fix of card data 0 or null

- src/components/insights/Layout/HeaderFilters/ModalFilters.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
Insights MVP
- Added grid template rows at modal filters container
> [ENGAGE-1063] - (Insights MVP) Fix of filters rows style

- src/components/insights/charts/BarChart.vue
- src/components/insights/charts/BaseChart.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Adicionada validação para remover os datalabels quando o valor da barra for zero.
- Ajustes de lint no BaseChart.
> [ENGAGE-1073] - (Insights MVP) Fix of BarChart zered labels

- src/components/TagGroup.vue
- src/components/insights/widgets/TableGroup.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Added TagGroup component to use when the value of the table_group content is an array;
- Formatted date value at TableGroup.
> [ENGAGE-1073] - (Insights MVP) Fix of widget TableGroup data formats

- src/components/insights/widgets/TableDynamicByFilter.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
Transformed into arrow functions values ​​within the redirect map so that they are not called as soon as the component accesses the object.
> [ENGAGE-1073] - (Insights MVP) Fix TableDynamicByFilter double redirect

- src/components/insights/Layout/Header.vue
- src/components/insights/Layout/HeaderFilters/ModalFilters.vue
- src/router/index.js
- src/store/modules/dashboards.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
* Fix today flag not show case filter date today
* Clear filters button disabled case not filters applied
* Adjustments to work in connect
* Filter not working in table group
> [ENGAGE-1063] - Fix review adjustments

- package.json
- src/components/insights/widgets/TableGroup.vue
- yarn.lock
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Update Unnnic version;
- Fixed pagination offset to start at 0 (first page)
- Fixed the paging interval bug when the last page was active and the request did not return a sufficient interval to calculate the total.
> [ENGAGE-1109] - (Insights MVP) Fix of TableGroup pagination

- src/components/insights/charts/BarChart.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Added a min height to bars of BarChart
> [ENGAGE-1109] - (Insights MVP) Configured BarChart bar min height

- src/components/insights/Layout/HeaderFilters/FilterSelect.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Added clear options function when filter select dependency value changes.
> [ENGAGE-1109] - (Insights MVP) Fix of permanence of select options when their dependency changes

- src/components/insights/cards/CardFunnel.vue
- src/components/insights/drawers/DrawerConfigWidgetDynamic.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/locales/translations.json
- src/services/api/resources/dashboards.js
- src/store/modules/dashboards.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Adjusted config card request body;
- Adjusted config graph funnel request body;
- Request card data after config it;
- Request graph funnel when is mounted and after config it.
> [ENGAGE-1151] - (Insights MVP) Fix drawers config request body

- src/components/insights/drawers/DrawerConfigContentFunnel.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Handle graph funnel config initial when drawer is mounted.
> [ENGAGE-1151] - (Insights MVP) Fix graph funnel initial config

- src/components/insights/cards/CardFunnel.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Fixed graph funnel data filtered
> [ENGAGE-1151] - (Insights MVP) Fix graph funnel data filtered

- src/components/insights/drawers/DrawerConfigContentCard.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Insights MVP
- Fixed drawer config card request body.
> [ENGAGE-1151] - (Insights MVP) Fix drawer config card request body

- src/store/modules/dashboards.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
InsightsMVP
- Removed static string for funnel cell titles;
- Added percentage calculation in funnel data values;
- Added ordering of highest result to least among the funnel data.
> [ENGAGE-1159] - (InsightsMVP) Ordering and formatting in graph funnel data

- src/components/insights/cards/CardFunnel.vue
- src/components/insights/drawers/DrawerConfigContentCard.vue
- src/components/insights/drawers/DrawerConfigWidgetDynamic.vue
- src/components/insights/widgets/DynamicWidget.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Flows Results Dashboards
* Change operations total value from 'total' to 'sum'
* Fix graph funnel not loading on handling filters
* Fix executions send operations other than 'count'
> [ENGAGE-1183] - Fix insights bugs

- src/components/insights/charts/HorizontalBarChart.vue
- src/components/insights/drawers/DrawerConfigWidgetDynamic.vue
- src/components/insights/widgets/DynamicWidget.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
InsightsMVP
- Fix HorizontalBar bars height;
- Fix HorizontalBar datas suffix.
> [ENGAGE-1159] - (Insights MVP) Fixes of HorizontalBar

- src/main.js
- src/utils/plugins/Hotjar.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Monitoring by session replay using Hotjar.
Added Hotjar script at main.
> [ENGAGE-1306] - Hotjar

- src/utils/plugins/Hotjar.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Hotjar in production only.
Added a validation to add hotjar only if have the id by enviroment variable.
> [ENGAGE-1306] - Hotjar in production only

- package.json
- src/components/insights/cards/CardDashboard.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/locales/translations.json
- src/models/Widget.ts
- src/models/types/WidgetTypes.ts
- yarn.lock
* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Apply the new visual pattern to the dashboard's card widgets
- Add friendly emoji
- Change settings button
- [Design File 1](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights?node-id=5987-23583&m=dev)
> [ENGAGE-1428] Refact widget card visual

- src/components/insights/Layout/Header.vue
- src/components/insights/Layout/HeaderGenerateInsights/HeaderGenerateInsightModal.vue
- src/components/insights/Layout/HeaderGenerateInsights/InsightModalFooter.vue
- src/components/insights/Layout/HeaderGenerateInsights/__tests__/HeaderGenerateInsightModal.spec.js
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Adjust comments logic, clickOutSide and NanValues in prompt
- comments logic, clickOutSide and NanValues
> [ENGAGE-1784] - Adjust comments logic, clickOutSide and NanValues in prompt - Generate Insights

- src/components/ModalResetWidget.vue
- src/components/insights/cards/CardFunnel.vue
- src/components/insights/cards/CardVtexOrder.vue
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/store/modules/widgets.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- adjust to match figma
- adjust css
> [ENGAGE-1852] Adjust design review

- src/components/ModalResetWidget.vue
- src/components/insights/cards/__tests__/CardEmpty.spec.js
- src/components/insights/drawers/DrawerConfigContentVtex.vue
- src/components/insights/drawers/DrawerConfigGallery/index.vue
- src/components/insights/drawers/DrawerConfigWidgetDynamic.vue
- src/components/insights/drawers/__tests__/DrawerConfigContentVtex.spec.js
- src/components/insights/widgets/DynamicWidget.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add feature vtex in specific projects
adding logic enabled vtex
> [ENGAGE-1937] Enabled vtex in especific projects

- src/components/insights/drawers/DrawerForms/Card/FormExecutions.vue
- src/components/insights/drawers/DrawerForms/Card/FormFlowResult.vue
- src/components/insights/drawers/DrawerForms/Card/__tests__/FormExecutions.spec.js
- src/components/insights/drawers/DrawerForms/Card/__tests__/FormFlowResult.spec.js
- src/utils/__tests__/time.spec.js
* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [X] Tests
* * [ ] Other
- frontend application coverage and security
- test suite creation
- pattern adjustments
> [ENGAGE-1889] - Form unit tests

- src/components/insights/charts/BaseChart.vue
- src/components/insights/charts/LineChart.vue
- src/components/insights/charts/loadings/SkeletonLineChart.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- New graph to human resources dashboard
- adding lineChart graph
- [Design File](https://www.figma.com/design/YLJ4Hjw9KgLlYO8L4qk853/Insights---Atendimento-humano?node-id=1-537&m=dev)
> [ENGAGE-1895] Add new peak graph 

- src/components/insights/widgets/DynamicWidget.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Normalization numbers
- function to normalization
> [ENGAGE-1877] Normalization number widget vtex

- src/components/insights/widgets/DynamicWidget.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
add normalization to orders
> [ENGAGE-1877] add normalization to orders

- src/components/insights/widgets/TableDynamicByFilter.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Adjust logic to redirect chats
Adjust logic to redirect chats
> [ENGAGE-1837] Redirect chats insights

- __tests__/components/__snapshots__/CheckboxList.spec.js.snap
- __tests__/layouts/__snapshots__/HeaderSelectDashboard.spec.js.snap
- __tests__/layouts/__snapshots__/OptionCreateNewDashboard.spec.js.snap
- __tests__/layouts/__snapshots__/OptionSelectDashboard.spec.js.snap
- package.json
- src/components/insights/cards/CardFunnel.vue
- src/components/insights/charts/FunnelChart.vue
- yarn.lock
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- New chart funnel
- adding new variant funnel
> [ENGAGE-1953] New chart funnel

- src/components/ModalResetWidget.vue
- src/components/insights/Layout/HeaderFilters/FilterSelectDate.vue
- src/components/insights/drawers/DrawerConfigContentFunnel.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- improve workflow funnel
- add reset widget logic
- add logic to remover four and five metrics
- add priority filter logic
- [Design File](https://www.figma.com/design/P9yyN4D0wGMlzYMjOtHvv3/Insights-MVP?node-id=5630-13992&t=x6BAwnlVjWAByyDr-1)
> [ENGAGE-2082] - Add reset widget to drawer funnel

- src/components/CompleteOnboardingModal.vue
- src/components/FormAccordion.vue
- src/components/ProgressBar.vue
- src/components/WelcomeOnboardingModal.vue
- src/components/__tests__/CompleteOnboardingModal.unit.spec.js
- src/components/__tests__/FormAccordion.unit.spec.js
- src/components/__tests__/ProgressBar.unit.spec.js
- src/components/__tests__/WelcomeOnboardingModal.unit.spec.js
- src/components/__tests__/__snapshots__/CompleteOnboardingModal.unit.spec.js.snap
- src/components/__tests__/__snapshots__/FormAccordion.unit.spec.js.snap
- src/components/__tests__/__snapshots__/ProgressBar.unit.spec.js.snap
- src/components/insights/charts/loadings/SkeletonBarChart.vue
- src/components/insights/charts/loadings/__tests__/SkeletonBarChart.unit.spec.js
- src/layouts/InsightsLayout.vue
- src/layouts/__tests__/InsightsLayout.unit.spec.js
- src/layouts/__tests__/__snapshots__/InsightsLayout.unit.spec.js.snap
- src/store/modules/__tests__/config.unit.spec.js
- src/store/modules/__tests__/project.unit.spec.js
- src/store/modules/__tests__/user.unit.spec.js
- src/utils/plugins/__tests__/Hotjar.unit.spec.js
- src/views/insights/__tests__/Report.unit.spec.js
- src/views/insights/__tests__/__snapshots__/Report.unit.spec.js.snap
* * [ ] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [X] Tests
* * [ ] Other
- frontend application coverage and security
- test suite creation
- pattern adjustments
> [ENGAGE-2053] Add more unit tests

- src/models/__tests__/Dashboard.spec.js
- src/models/__tests__/Filters.spec.js
- src/models/__tests__/Widget.spec.js
- src/models/__tests__/WidgetOutgoing.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase tests coverage at the application.
Added tests of all models.
> [CFE-463] - Models tests

- src/components/insights/drawers/DrawerConfigGallery/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add vtex access cencosud
add new id
> [ENGAGE-2057] add vtex access cencosud

- src/components/insights/cards/CardDashboard.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/components/insights/widgets/__tests__/DynamicWidget.spec.js
* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [x] Tests
* * [ ] Other
Increase application tests coverage.
- Added DynamicWidget tests;
- Fixed `CardDashboard` component name.
> [CFE-491] - DynamicWidget tests

- src/components/insights/widgets/TableGroup.vue
- src/components/insights/widgets/__tests__/TableGroup.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase application tests coverage.
Added TableGroup tests.
> [CFE-491] - TableGroup tests

- src/components/insights/drawers/DrawerConfigGallery/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add new projects to use vtex cards
- add new project id's
> [ENGAGE-2277] - add new projects to use vtex card

- src/components/home/CardMetric.vue
- src/components/home/DropdownFilter.vue
- src/components/home/__tests__/CardMetric.spec.js
- src/components/home/__tests__/DropdownFilter.spec.js
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/utils/__tests__/numbers.spec.js
- src/utils/numbers.ts
- src/views/insights/DashboardCommerce.vue
- src/views/insights/__tests__/DashboardCommerce.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- Add data skills components to  plataform 1.5
- adding DashboardCommerce
- adding CardMetric 
- adding Filter
- [Design File 1](https://www.figma.com/design/b5K427ZyxboscTyXlqTZOJ/Home?node-id=93-86&m=dev)
> [ENGAGE-2466] Data skills components and filter

- docker/Dockerfile
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix docker file config
- fix CI
> fix docker file config

- src/components/insights/cards/CardDashboard.vue
- src/components/insights/widgets/DynamicWidget.vue
- src/components/insights/widgets/__tests__/DynamicWidget.spec.js
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [X] Tests
* * [ ] Other
- Add new tooltips to helper users
- add tooltip to cardDashboard
- add translations
- add tests
- [Design File](https://www.figma.com/design/YLJ4Hjw9KgLlYO8L4qk853/Insights---Atendimento-humano?node-id=269-4260&m=dev)
> [ENGAGE-2558] add tooltips human dashboard

- src/components/insights/cards/CardRecurrence.vue
- src/components/insights/drawers/DrawerConfigContentRecurrence.vue
- src/components/insights/drawers/DrawerConfigWidgetDynamic.vue
- src/components/insights/widgets/DynamicWidget.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Improvement in see more logic, align progress bar and adjust validForm
- adjust see more logic
- align progress bar
- adjust validForm verify
> [ENGAGE-2586] Adjust logic see more and align progress bar

- src/components/insights/drawers/DrawerConfigGallery/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add new projet to consumer widget vtex
- add new project id
> [ENGAGE- 2917] add new project id to vtex widget

- .github/workflows/build-insights-webapp-push-tag-shared.yaml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Addition of steps for environment variables to be processed in the build stage
> ajust build

- .github/workflows/build-insights-webapp-push-tag-shared.yaml
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
> change path manifests environment

- src/components/insights/widgets/ExpansiveWidget.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- improvement to update expansive logic agents
- add pool logic
> [ENGAGE-2827]  update logic one minute to expansive widget

- docker-entrypoint.sh
- package-lock.json
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- resolve break because window.config logic
> fix docker-entrypoint to set window.config

- src/components/insights/widgets/HumanServiceAgentsTable/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
convert days to hours
convert days to hours
> fix convert hours

- src/components/insights/drawers/DrawerConfigGallery/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- ADD new project
- ADD new project
> [ENGAGE-3120] add new project to view vtex

- src/components/insights/drawers/DrawerConfigGallery/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- enable new projects id
- new project id's
> [ENGAGE-3188] - Add new projects to use widget vtex

- package-lock.json
- src/services/api/http.js
- src/services/api/resources/metrics.js
- src/views/insights/DashboardCommerce.vue
- src/views/insights/__tests__/DashboardCommerce.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- To use getMetrics api
- Auth logic
- Tests component
> [ENGAGE-3185] - Auth logic module federation

- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/views/insights/DashboardCommerce.vue
- src/views/insights/__tests__/DashboardCommerce.spec.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- improve user experience with error to get data
- add error logic and translations
- [Design File 1](https://www.figma.com/design/b5K427ZyxboscTyXlqTZOJ/Plataforma-1.5---Home?node-id=1426-4189&m=dev)
> [ENGAGE-3302] Improve error logic dashboard commerce

- src/components/insights/cards/CardRecurrence.vue
- src/components/insights/cards/__tests__/CardRecurrence.spec.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- update to be more faithful to the design in some situations
- adding new logic style
- adding new tests
- adjusting tests
- [Design File 1](https://www.figma.com/design/8OGWFgNdEVzQ1Ga4IFZ4Sg/Insights---Dashboard-resultado-de-fluxos?node-id=876-2715&m=dev)
> [ENGAGE-2838] Widget recurrence treatment with few results

- src/App.vue
- src/components/insights/drawers/DrawerConfigGallery/index.vue
- src/store/modules/project.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- fluid flow to commerce vtex projects
- add new event and verify to widget vtex render
> [ENGAGE-3270] Integrate widget vtex in commerce projects

- src/components/insights/widgets/HumanServiceAgentsTable/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Improve status agent logic
- add new status logic 
> [ENGAGE-3259] Add new logic status

- src/views/insights/DashboardCommerce.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add error logic again to dashboard commerce
- add error logic
> [ENGAGE-3498] Add error logic again dashboard commerce

- src/components/insights/widgets/HumanServiceAgentsTable/AgentsTableHeader.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
fix source name
- adjusting source name
> fix/ source filter

- .github/workflows/build-insights-webapp-push-tag-shared.yaml
* * [ ] Bugfix
* * [x] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Reusable workflows in GitHub Actions bring modularity to pipeline design, enabling parameterized reuse even across repositories
> Cloud 2442

- src/components/insights/widgets/HumanServiceAgentsTable/__tests__/HumanServiceAgentsTable.spec.js
- src/components/insights/widgets/HumanServiceAgentsTable/index.vue
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
Fix order in_progress e closeds orders
Fix order in_progress e closeds orders
> [ENGAGE] Fix order in_progress e closeds orders

- src/components/insights/widgets/HumanServiceAgentsTable/AgentsTableHeader.vue
- src/components/insights/widgets/HumanServiceAgentsTable/__tests__/AgentsTableHeader.unit.spec.js
* * [X] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
- code improvements and refactorings related to the life cycle of the multi select component
- Adding new logics
- Adding more tests
> [ENGAGE-3809] Refactoring/logic and tests agents table header

- src/services/api/http.js
- src/utils/pinia-setup.js
- src/views/insights/DashboardCommerce.vue
- src/views/insights/__tests__/DashboardCommerce.spec.js
…alization
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Fix get metrics error
- add pinia-setup with module federation
> [ENGAGE-4086] Fix problem get metrics

- src/components/insights/widgets/DynamicWidget.vue
- src/components/insights/widgets/__tests__/DynamicWidget.spec.js
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/store/modules/__tests__/reports.unit.spec.js
- src/store/modules/reports.ts
* * [X] Bugfix
* * [ ] Tests
* * [ ] Other
- Add treatment for get data error
- add logic to render error for users
> [ENGAGE-4088] Fix dashboard get data error

- src/components/TagGroup.vue
- src/components/__tests__/TagGroup.spec.js
- src/components/insights/Layout/HeaderFilters/FilterMultiSelect.vue
- src/components/insights/Layout/HeaderFilters/__tests__/FilterMultiSelect.spec.js
- src/components/insights/Layout/HeaderFilters/__tests__/FilterSelectDate.spec.js
- src/components/insights/drawers/DrawerForms/Card/FormDataCrossing/__tests__/FormDataCrossing.spec.js
- src/components/insights/drawers/__tests__/DrawerConfigWidgetDynamic.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Increase tests coverage
- Add FormDataCrossing tests
- Add DrawerConfigWidgetDynamic tests
> [ENGAGE-4150] Increase tests coverage

- src/components/ProgressItem.vue
- src/components/__tests__/ProgressItem.spec.js
- src/components/insights/charts/NativeProgress.vue
- src/components/insights/charts/__tests__/NativeProgress.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- add new components to use
- add more tests
- [Design File 1](https://www.figma.com/design/aN8dbWdTMWAYlPA4t4o51D/Conversational-Data-Dashboards--4388-?node-id=476-8901&m=dev)
> [ENGEAGE-4472] Add conversational progress bar components

- src/components/insights/drawers/DrawerConfigGallery/index.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
- add new project uuid
- add new project uuid
> [ENGAGE-4582] add new project uuid to use widget vtex

- package-lock.json
- package.json
- src/components/insights/charts/TreemapChart.vue
- src/components/insights/charts/__tests__/TreemapChart.spec.js
- src/components/insights/conversations/MostTalkedAboutTopics.vue
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/utils/__tests__/treemap.spec.js
- src/utils/treemap.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
> [NEXUS-3114] - (Dashboard conversational) Treemap chart

- src/components/ProgressTable.vue
- src/components/ProgressTableRow.vue
- src/components/ProgressTableRowItem.vue
- src/components/__tests__/ProgressITableRowItem.spec.js
- src/components/__tests__/ProgressTable.spec.js
- src/components/__tests__/ProgressTableRow.spec.js
- src/components/__tests__/ProgressTableRowItem.spec.js
- src/components/__tests__/__snapshots__/ProgressTable.spec.js.snap
- src/components/insights/charts/NativeProgress.vue
- src/components/insights/charts/TreemapChart.vue
- src/components/insights/charts/__tests__/NativeProgress.spec.js
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/SeeAllDrawer.vue
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/index.vue
- src/components/insights/dashboards/Conversational.vue
- src/components/insights/widgets/ProgressWidget.vue
- src/components/insights/widgets/__tests__/ProgressWidget.spec.js
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
(Dashboard Conversational) Drawer of most talked about topics
- Enhance ProgressTable and ProgressTableRow components with expandable functionality and introduce ProgressTableRowItem for improved structure;
- Add TreemapChart onHover event and improve onClick handling
- Added tests to new functionallities.
- [Design File](https://www.figma.com/design/aN8dbWdTMWAYlPA4t4o51D/Insights---Conversational-Data-Dashboards--4388-?node-id=576-14181&m=dev)
> [NEXUS-3440] - (Dashboard Conversational) Drawer of most talked about topics

- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/services/api/resources/dashboards.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
Add translations to the conversational dashboard name
Add translations for conversations dashboard
> [NEXUS-3478] - (Dashboard conversational) Dashboard name translations

- src/components/insights/conversations/DashboardHeader.vue
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/SeeAllDrawer.vue
- src/components/insights/conversations/__tests__/DashboardHeader.spec.js
- src/services/api/resources/conversational/__tests__/header.spec.js
- src/services/api/resources/conversational/header.ts
* * [x] Bugfix
* * [x] Tests
* * [ ] Other
- Add api logic to integrate
- add logic integration header
- add tests
> [ENGAGE-4632] Integrate backend dashboard conversational header

- src/components/insights/conversations/DashboardHeader.vue
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/SeeAllDrawer.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add format value to components needed
- add format value to components
> [ENGAGE-4635] Utils format value to dashboard conversational

- src/components/insights/conversations/topics/DrawerTopics.vue
- src/components/insights/conversations/topics/Form/FormTopicItem.vue
- src/components/insights/conversations/topics/ModalTopic.vue
- src/components/insights/conversations/topics/__tests__/DrawerTopics.spec.js
- src/components/insights/dashboards/Conversational.vue
- src/components/insights/dashboards/__tests__/Conversational.spec.js
- src/store/modules/conversational/__tests__/topics.spec.js
- src/store/modules/conversational/topics.ts
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- add logic to enable/disabled btn drawer topics
- add verifiy logics in store
- add to drawer
- add tests
> [ENGAGE-4634] Enable btns form topics

- src/components/insights/conversations/DashboardHeader.vue
- src/components/insights/conversations/__tests__/DashboardHeader.spec.js
- src/services/api/resources/conversational/__tests__/header.spec.js
- src/services/api/resources/conversational/header.ts
- src/store/modules/conversational/__tests__/conversational.spec.js
- src/store/modules/conversational/conversational.ts
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- add logic to update request after query change
- adjust header loading logic
- adjust header request load
- adjust header api logic
- add conversational store to formatting filters
- adjust tests
> [ENGAGE-4660] Add conversational filter logic to header integration

- src/components/ProgressTable.vue
- src/components/insights/charts/TreemapChart.vue
- src/components/insights/charts/__tests__/TreemapChart.spec.js
- src/components/insights/conversations/BaseConversationWidget.vue
- src/components/insights/conversations/ConversationalDynamicWidget.vue
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/SeeAllDrawer.vue
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/index.vue
- src/components/insights/conversations/topics/DrawerTopics.vue
- src/components/insights/conversations/topics/Form/FormTopic.vue
- src/components/insights/conversations/topics/Form/__tests__/FormTopic.spec.js
- src/components/insights/conversations/topics/__tests__/DrawerTopics.spec.js
- src/components/insights/dashboards/Conversational.vue
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/services/api/resources/__tests__/dashboard.spec.js
- src/services/api/resources/conversational/__tests__/topics.spec.js
- src/services/api/resources/conversational/topics.ts
- src/services/api/resources/dashboards.js
- src/store/modules/conversational/__tests__/topics.spec.js
- src/store/modules/conversational/topics.ts
- src/utils/treemap.ts
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
Integrate backend Topics, to real use.
- Integrate backend Topics
- add many tests and services
> [ENGAGE-4633] Integrate backend Topics

- src/components/ProgressTableRowItem.vue
… text handling
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Add nowrap to description in ProgressTableRowItem for improved
- add new style to no wrap description
> [ENGAGE-4588] Add nowrap to description in ProgressTableRowItem for improved

- src/components/insights/conversations/ConversationalDynamicWidget.vue
- src/components/insights/conversations/CsatOrNpsWidget/ConfigCsatOrNps.vue
* * [X] Bugfix
* * [X] Refactoring (no functional changes, no api changes)
* * [ ] Tests
* * [ ] Other
Improve csat/nps dashboard conversational
- add query render logic and fix form
> [ENGAGE-4705] Feat/add query render logic and fix form

- src/components/ProgressTableRowItem.vue
- src/components/insights/cards/CardConversations.vue
- src/components/insights/conversations/ConversationalDynamicWidget.vue
- src/components/insights/conversations/CsatOrNpsWidget/ModalRemoveWidget.vue
- src/components/insights/conversations/DashboardHeader.vue
- src/components/insights/conversations/MostTalkedAboutTopicsWidget/index.vue
- src/components/insights/conversations/topics/Form/FormTopicCard.vue
- src/components/insights/widgets/ProgressWidget.vue
* * [ ] Bugfix
* * [ ] Tests
* * [x] Other
* Added loading state to the remove widget modal button
* Fixed incorrect uppercase formatting in the type dropdown for CSAT and NPS widget editing
* Fixed the 100-character limit incorrectly applied to the topic context field
* Adjusted inconsistent spacing: the first created topic had less margin than subsequent ones
* Disabled "See all" option in the treemap while loading
* Added translations to the tabs of unconfigured CSAT and NPS widget variations
> [NEXUS-3523] - (Dashboard conversational) Fix some styles

- src/components/insights/cards/CardConversations.vue
- src/components/insights/conversations/DashboardHeader.vue
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
To improve the user experience of understanding the data, it was necessary to redirect the user to the Supervisor so that they could see the conversations for each data item.
Enhance dashboard conversational cards to redirect from supervisor conversations
> [NEXUS-3518] - (Dashboard Conversational) Redirect header cards from Supervisor

- src/store/modules/conversational/__tests__/topics.spec.js
- src/store/modules/conversational/topics.ts
- src/utils/__tests__/topics.spec.js
- src/utils/topics.ts
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- Improve logic to enable save changes btn
- add new function to check variables
- adjust tests
> [ENGAGE-4732] (Dashboard Conversational) Improve logic is empty values in save change topics

- src/App.vue
- src/__tests__/App.spec.js
- src/components/WelcomeOnboardingModal.vue
- src/components/insights/dashboards/DashboardCustom.vue
- src/components/insights/dashboards/TemplateMessageMeta.vue
- src/components/insights/dashboards/__tests__/DashboardCustom.spec.js
- src/components/insights/dashboards/__tests__/TemplateMessageMeta.spec.js
- src/components/insights/drawers/DrawerConfigWidgetDynamic.vue
- src/components/insights/drawers/__tests__/DrawerConfigWidgetDynamic.spec.js
- src/main.js
- src/store/modules/__tests__/agentsColumnsFilter.unit.spec.js
- src/store/modules/__tests__/config.unit.spec.js
- src/store/modules/agentsColumnsFilter.ts
- src/store/modules/config.ts
- src/utils/__tests__/jwt.spec.js
- src/utils/__tests__/storage.spec.js
- src/utils/jwt.js
- src/utils/storage.js
* * [ ] Bugfix
* * [x] Code style update (formatting, local variables)
* * [x] Tests
* * [ ] Other
- improvement storage logic to better support the module federation
- add utils class storage
- adjust imports use localstorage
> [ENGAGE-4860] Feat add prefix 'insights' to storage

- package-lock.json
- package.json
- src/components/WarningMessage.vue
- src/components/insights/conversations/BaseConversationWidget.vue
- src/components/insights/conversations/ConversationalDynamicWidget.vue
- src/components/insights/conversations/WidgetError.vue
- src/components/insights/dashboards/Conversational.vue
- src/components/insights/widgets/ProgressWidget.vue
- src/locales/en.json
- src/locales/es.json
- src/locales/pt_br.json
- src/store/modules/conversational/customWidgets.ts
- src/store/modules/conversational/widgets.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- add logic to render errors to get data on widgets
- add error components
- add errors logics
- [Design File 1](https://www.figma.com/design/aN8dbWdTMWAYlPA4t4o51D/Insights---Conversational-Data-Dashboards--4388-?node-id=1393-23932&m=dev)
> [ENGAGE-4921] (Conversational Dashboard) Add errors variant to widgets

- package-lock.json
- package.json
- src/components/SelectEmojiButton.vue
- src/components/__tests__/SelectEmojiButton.spec.js
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- Fix/emoji picker on module federation
- update unnnic system to use new emoji picker
- add locale to translate
> [ENGAGE-5146] Fix/emoji picker on module federation

- src/App.vue
- src/__tests__/App.spec.js
- src/services/api/resources/featureFlag/__tests__/featureFlag.spec.js
- src/services/api/resources/featureFlag/featureFlag.ts
- src/store/modules/__tests__/featureFlag.unit.spec.js
- src/store/modules/featureFlag.ts
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- Add feature flag to project
- add store feature logic
- add service to get feature flag
- add logic in App.vue to get feature flags
> [ENGAGE-5298] Add feature flag to project

- src/components/insights/Layout/HeaderFilters/FilterDate.vue
- src/utils/treemap.ts
* * [x] Bugfix
* * [ ] Tests
* * [ ] Other
- Dashboard conversational minor fixes
- removing data select limit
- adjust others translation
> [ENGAGE-5157] Dashboard conversational minor fixes

- src/components/insights/widgets/HumanServiceAgentsTable/AgentStatus.vue
- src/components/insights/widgets/HumanServiceAgentsTable/__tests__/AgentStatus.unit.spec.js
* * [ ] Bugfix
* * [x] Tests
* * [ ] Other
- add logic to disconnect custom status
- add logic to disconnect custom status
- add tests
> [ENGAGE-5317] Disconnect agent status pause

- src/components/insights/Layout/Header.vue
- src/services/api/resources/export/conversational/export.ts
- src/store/modules/export/conversational/export.ts
* * [ ] Bugfix
* * [ ] Tests
* * [ ] Other
- improve for users export conversational data
- adjusting logic to integration
> [ENGAGE-5183] (Dashboard Conversational) export integration
